export const INCIDENT_TYPES = [
  'Unauthorized Access to Building',
  'Vandalism or Property Damage',
  'Theft in Common Areas',
  'Parking Lot Vandalism or Theft',
  'Vehicle Damage or Accident in Parking Area',
  'Suspicious Person or Activity',
  'Disturbance or Noise Complaint',
  'Medical Emergency within Building or Parking Lot',
  'Fire or Smoke Alarm Activation',
  'False Alarm or Malfunction',
  'Elevator Malfunction or Incident',
  'Security Breach (Broken Access Control)',
  'Lost or Missing Person',
  'Disruptive or Inappropriate Behavior',
  'Emergency Lockdown or Evacuation',
  'Damage to Building Fixtures or Common Areas',
  'Accessory or Equipment Theft',
  'Unauthorized Parking or Violations',
  'Resident Dispute or Altercation',
  'Hazardous Condition',
  'Suspicious Package or Object',
  'Fire Drills or Safety Inspection Issue',
  'Other'
]

export const INCIDENT_LOCATIONS = [
  'Main Entrance',
  'Lobby',
  'Elevator',
  'Stairwell',
  'Parking Garage',
  'Parking Lot',
  'Mailroom',
  'Laundry Room',
  'Common Area',
  'Hallway',
  'Balcony',
  'Pool Area',
  'Gym/Fitness Center',
  'Storage Area',
  'Roof',
  'Outside Property',
  'Other'
]